In [1]:
import sys
sys.path.append('../')
import torch
from Code.NewNeurons import CooldownNeuron, NoResetNeuron, LIFNeuron
from matplotlib import pyplot as plt
%matplotlib
import json
import csv


Using matplotlib backend: TkAgg


In [2]:
x = torch.linspace(-1, 1, 100)
plt.plot(x, torch.sigmoid(x*5), linewidth=3, linestyle='dashed')
plt.plot(x, (x>0).float(), linewidth=3)

In [6]:
daba = ['config2', 'top1_0', 'lifonlynr1', 'lstm1']
id = 'config40'

with open(f'../configs/{id}.json', 'r') as config_file:
    config = json.load(config_file)
    stats = config['stats']

with open(f'../export/{id}.csv', 'w') as csvfile: #, newline=''
    spamwriter = csv.writer(csvfile, delimiter=' ',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    spamwriter.writerows(enumerate(stats['val']))

In [5]:
list()

[(0, 0.09648437798023224),
 (1, 0.56982421875),
 (2, 0.675976574420929),
 (3, 0.7259765863418579),
 (4, 0.779492199420929),
 (5, 0.7613281607627869),
 (6, 0.819531261920929),
 (7, 0.812695324420929),
 (8, 0.8534179925918579),
 (9, 0.868359386920929),
 (10, 0.8946289420127869),
 (11, 0.892871081829071),
 (12, 0.9013671875),
 (13, 0.9212890863418579),
 (14, 0.929980456829071),
 (15, 0.92626953125),
 (16, 0.9351562857627869),
 (17, 0.9375),
 (18, 0.9388672113418579),
 (19, 0.941699206829071),
 (20, 0.939160168170929),
 (21, 0.952441394329071),
 (22, 0.953320324420929),
 (23, 0.9512695670127869),
 (24, 0.9560546875),
 (25, 0.9571289420127869),
 (26, 0.9603515863418579),
 (27, 0.9560546875),
 (28, 0.962597668170929),
 (29, 0.9588867425918579),
 (30, 0.966503918170929),
 (31, 0.9517578482627869),
 (32, 0.966015636920929),
 (33, 0.96875),
 (34, 0.9681640863418579),
 (35, 0.9657226800918579),
 (36, 0.9644531607627869),
 (37, 0.962109386920929),
 (38, 0.9615234732627869),
 (39, 0.96328127384185

In [35]:

n = 288#75
ids = ['auto1_'+str(x) for x in range(n)]
#ids = [f'config{x}' for x in range(41)]

buckets = 10
attribute = 'spkfn'
value = 'ss'

data = torch.zeros([buckets, 2])
data[:, 0] = torch.arange(buckets, dtype=torch.float)/buckets + 1/(2*buckets)

for id in ids:
    with open('../configs/'+id+'.json', 'r') as config_file:
        config = json.load(config_file)
        if config['params'][attribute] == value:
            bucket = int(config['stats']['val'][-1] * buckets * 0.9999)
            data[bucket, 1] += 1

with open(f'../export/{value}.csv', 'w') as csvfile: #, newline=''
    spamwriter = csv.writer(csvfile, delimiter=' ',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    spamwriter.writerows(data.tolist())

In [26]:
data

tensor([[5.0000e-02, 0.0000e+00],
        [1.5000e-01, 5.1000e+01],
        [2.5000e-01, 4.0000e+00],
        [3.5000e-01, 5.0000e+00],
        [4.5000e-01, 8.0000e+00],
        [5.5000e-01, 6.0000e+00],
        [6.5000e-01, 9.0000e+00],
        [7.5000e-01, 6.0000e+00],
        [8.5000e-01, 6.0000e+00],
        [9.5000e-01, 1.0000e+00]])

In [9]:
id = 'auto1_0'

with open(f'../configs/{id}.json', 'r') as config_file:
    config = json.load(config_file)
    stats = config['stats']

torch.tensor(stats['val'][-20:]).mean()

tensor(0.1517)

In [12]:
len(stats['val'])

11

In [13]:
len(stats['acc'])

5148

In [30]:
ind = [1,3,4,5,6,7,8,9,10]
#neuron = 'adap'

ids = [f'sm_adap_durs{x}' for x in ind]
#ids = [f'config{x}' for x in range(41)]


data = torch.zeros([len(ind)+4, 2])
data[:len(ind), 0] = torch.arange(len(ind), dtype=torch.float)*2 + 2
i = 0
for id in ids:
    with open('../configs/'+id+'.json', 'r') as config_file:
        config = json.load(config_file)
        data[i, 1] = config['stats']['val'][-1]
    i += 1

data[-4:, 0] = torch.tensor([20,30,40,50])

ids = [f'sm_adap_adjs{x}' for x in range(4)]
for id in ids:
    with open('../configs/'+id+'.json', 'r') as config_file:
        config = json.load(config_file)
        data[i, 1] = config['stats']['val'][-1]
    i += 1

ids = [f'sm_adap_short{x}' for x in range(2)]
i = 0
for id in ids:
    with open('../configs/'+id+'.json', 'r') as config_file:
        config = json.load(config_file)
        data[i, 1] = config['stats']['val'][-1]
    i += 1


In [31]:
data

tensor([[ 2.0000,  0.8036],
        [ 4.0000,  0.8309],
        [ 6.0000,  0.9724],
        [ 8.0000,  0.9911],
        [10.0000,  0.9970],
        [12.0000,  0.9913],
        [14.0000,  0.9970],
        [16.0000,  0.9972],
        [18.0000,  0.9941],
        [20.0000,  0.9964],
        [30.0000,  0.9893],
        [40.0000,  0.9858],
        [50.0000,  0.9240]])

In [4]:

with open(f'../export/sm_nores.csv', 'w') as csvfile: #, newline=''
    spamwriter = csv.writer(csvfile, delimiter=' ',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    spamwriter.writerows(data.tolist())

In [3]:

data = torch.zeros([13, 2])
data[:9, 0] = torch.arange(9, dtype=torch.float)*2 + 2
i = 0


data[-4:, 0] = torch.tensor([20,30,40,50])

ids = [f'sm_nores_durs{x}' for x in range(13)]
for id in ids:
    with open('../configs/'+id+'.json', 'r') as config_file:
        config = json.load(config_file)
        data[i, 1] = config['stats']['val'][-1]
    i += 1

In [5]:

data

tensor([[ 2.0000,  0.7870],
        [ 4.0000,  0.8848],
        [ 6.0000,  0.9605],
        [ 8.0000,  0.9862],
        [10.0000,  0.9942],
        [12.0000,  0.9967],
        [14.0000,  0.9967],
        [16.0000,  0.9972],
        [18.0000,  0.9971],
        [20.0000,  0.9984],
        [30.0000,  0.9988],
        [40.0000,  0.9976],
        [50.0000,  0.9958]])

In [18]:
with open('../export/config40.csv', 'r') as csvfile: #, newline=''
    reader = csv.reader(csvfile, delimiter=' ',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    data = list(reader)

In [19]:
for row in data:
    row[1] = 1 - float(row[1])

In [20]:
with open('../export/config40_rev.csv', 'w') as csvfile: #, newline=''
    spamwriter = csv.writer(csvfile, delimiter=' ',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    spamwriter.writerows(data)