In [1]:
import sys
sys.path.append('../')
from torch.distributions.bernoulli import Bernoulli
from torch.distributions.geometric import Geometric
from Code.envs.permutations import make_permutations, encode_perm, make_batch
import torch
import torch.nn as nn
import torch.optim as optim
import time
from collections import OrderedDict

from PIL import Image
import numpy as np

In [2]:
device = torch.device('cpu')


In [16]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [17]:
ind = torch.tensor([[1], [0], [2]])

In [24]:
b = torch.zeros([3,3], dtype=torch.long)

In [25]:
a.scatter(1, ind, b)

tensor([[1, 0, 3],
        [0, 5, 6],
        [7, 8, 0]])

In [9]:
a.shape

torch.Size([3, 3])

In [28]:
a.unsqueeze(-1).shape

torch.Size([3, 3, 1])

In [7]:
data = make_permutations(9, device)

In [8]:
data.shape

torch.Size([2, 9, 5])

In [9]:
conv = encode_perm(data)

In [10]:
conv.shape

torch.Size([2, 9, 5, 5])

In [14]:
conv[0,0]

tensor([[0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

In [15]:
data[0,0]

tensor([4, 1, 0, 2, 3])

In [3]:
store_dist = (lambda : Geometric(torch.tensor([0.2], device=device)).sample().int().item()+1)
every_dist = (lambda : 1)

In [5]:
make_batch(1, 20, store_dist, device)

(tensor([[[0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
           0., 0., 0., 1., 0., 1., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
           0., 0., 0., 0., 0., 0., 0., 1., 0.]],
 
         [[0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1.,
           0., 0., 0., 0., 0., 0., 0., 0., 1.]],
 
         [[0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
           0., 0., 0., 1., 1., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
           0., 0., 1., 0., 0., 0., 1., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
           0., 0., 0., 0., 0., 0., 0., 1., 0.]],
 
         [[0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
           1., 0., 0., 0., 1., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
           

In [29]:
c = torch.tensor([0,1,2,3,4])
i = torch.tensor([2,3,0,1,4])

In [30]:
c[i] = c * 1

In [31]:
c

tensor([2, 3, 0, 1, 4])

In [18]:
c = torch.tensor([0,1,2,3,4]).unsqueeze(0)
i = torch.tensor([3,2,0,1,4]).unsqueeze(0)

In [19]:
d = torch.empty_like(c)

In [26]:
d.scatter_(-1, i, c)

tensor([[2, 3, 1, 0, 4]])

In [24]:
d[:, i[0]] = c

In [27]:
d

tensor([[2, 3, 1, 0, 4]])

In [52]:
i[c]

tensor([0, 1, 2, 3, 4])

In [53]:
c[i]

tensor([0, 1, 2, 3, 4])